version: '3.3'

volumes:
   pg_data:
   static:
   media:

services:
   db:
     env_file: .env
     image: postgres:13
     volumes:
       - pg_data:/var/lib/postgresql/data/
     restart: always

   backend:
     env_file: .env
     image: klenyushin94/foodgram_backend
     volumes:
       - static:/app/backend_static/
       - media:/app/media/
     depends_on:
       - db
     restart: always

   frontend:
     image: klenyushin94/foodgram_frontend
     command: cp -r /app/build/. /app/static/
     volumes:
       - static:/app/static/

   nginx:
     image: klenyushin94/foodgram_nginx
     ports:
       - 8001:80
     volumes:
       - static:/app/static/
       - media:/app/media/
     depends_on:
       - backend
       - frontend
     restart: always