# Generated by Django 2.2.19 on 2023-09-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='amount',
            new_name='ammount',
        ),
    ]
