# Generated by Django 2.2.19 on 2023-09-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230908_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ammount',
            new_name='amount',
        ),
    ]
