# Generated by Django 4.2.5 on 2023-09-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='is_in_shopping_cart',
        ),
    ]
